brd_ctrl.o: brd_ctrl.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h p1516cl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/sim.src/memcl.h \
 brd_ctrlcl.h ../../../src/core/sim.src/hwcl.h
clock.o: clock.cc clockcl.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/brkcl.h ../../../src/core/sim.src/stackcl.h \
 ../../../src/core/sim.src/varcl.h ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h
fpga.o: fpga.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h p1516cl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/sim.src/memcl.h \
 fpgacl.h ../../../src/core/sim.src/hwcl.h
glob.o: glob.cc glob.h ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h
p1516.o: p1516.cc ../../../src/core/sim.src/dregcl.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h glob.h portcl.h \
 ../../../src/core/sim.src/port_hwcl.h uartcl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/sim.src/serial_hwcl.h \
 clockcl.h ../../../src/core/sim.src/hwcl.h timercl.h fpgacl.h \
 brd_ctrlcl.h p1516cl.h ../../../src/core/sim.src/memcl.h
p2223.o: p2223.cc glob.h ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h pmon.h p2223cl.h p1516cl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/sim.src/brkcl.h ../../../src/core/sim.src/stackcl.h \
 ../../../src/core/sim.src/varcl.h ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/memcl.h
pmon.o: pmon.cc pmon.h ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h
port.o: port.cc portcl.h ../../../src/core/sim.src/port_hwcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/cmdutil.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/sim.src/memcl.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h
simp1516.o: simp1516.cc simp1516cl.h ../../../src/core/sim.src/simcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h p1516cl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/sim.src/memcl.h \
 p2223cl.h glob.h
sp1516.o: sp1516.cc ../../../src/core/utils.src/globals.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/utils.src/appcl.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/optioncl.h ../../../src/core/sim.src/argcl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/simcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h ../../../src/core/gui.src/guicl.h \
 ../../../src/core/gui.src/ifcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/argcl.h ../../../src/core/utils.src/utils.h \
 ../../../src/core/utils.src/fiocl.h simp1516cl.h glob.h
timer.o: timer.cc timercl.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjcl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/uccl.h \
 ../../../src/core/utils.src/pobjt.h ../../../src/core/sim.src/hwcl.h \
 ../../../src/core/sim.src/brkcl.h ../../../src/core/sim.src/stackcl.h \
 ../../../src/core/sim.src/varcl.h ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h
uart.o: uart.cc ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/sim.src/argcl.h ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/ddconfig.h \
 ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/charscl.h \
 ../../../src/core/utils.src/stypes.h ../../../src/core/sim.src/itsrccl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/utils.src/pobjt.h \
 ../../../src/core/sim.src/hwcl.h ../../../src/core/sim.src/guiobjcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/utils.src/optioncl.h \
 ../../../src/core/utils.src/pobjcl.h \
 ../../../src/core/utils.src/stypes.h \
 ../../../src/core/cmd.src/commandcl.h \
 ../../../src/core/cmd.src/newcmdcl.h \
 ../../../src/core/cmd.src/newcmdposixcl.h \
 ../../../src/core/utils.src/fiocl.h ../../../src/core/cmd.src/cmdutil.h \
 ../../../src/core/sim.src/memcl.h ../../../src/core/utils.src/eventcl.h \
 ../../../src/core/utils.src/errorcl.h ../../../src/core/sim.src/brkcl.h \
 ../../../src/core/sim.src/stackcl.h ../../../src/core/sim.src/varcl.h \
 ../../../src/core/sim.src/itabcl.h \
 ../../../src/core/sim.src/uccl_instructions.h \
 ../../../src/core/sim.src/itsrccl.h uartcl.h \
 ../../../src/core/sim.src/uccl.h ../../../src/core/sim.src/serial_hwcl.h
